### ISSUE TITLE
Cloudflareにてアプリケーションのビルドで失敗する

### ISSUE THREAD

**Issue by Rinrin0413** [Rinrin0413/svelte-etude.dev#1]
# 原因がわからない( ；∀；)
https://discord.com/channels/874921679707594774/874921680164761653/912303055880478720
<html>
<body>

20:25:31.931 | > 404 /src/routes/style.scss (linked from /)
-- | --
20:25:31.931 | Error: 404 /src/routes/style.scss (linked from /)

</body>
</html>
って言われる(´；ω；｀)

**Comment by Rinrin0413** [comment]
### Cloudflare側の環境変数"NODE_VERSION"の値を15から16に変えてみたがエラー

<html>
<body>
<pre class="c_b c_bn c_nq c_nr c_ow c_ox c_cx c_pk c_mb c_lz c_ma c_fd c_fe c_bp c_oy" style="box-sizing: border-box; border-radius: 0px; color: rgb(217, 217, 217); display: block; font-size: 12px; margin: 0px; overflow: auto; padding: 16px 32px; width: 1021.97px; background-color: rgb(29, 29, 29); border-width: 0px 0px 1px; border-style: solid; border-color: rgb(61, 61, 61) rgb(61, 61, 61) rgb(49, 49, 49); border-image: initial; font-family: monaco, courier, monospace; height: 500px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

20:45:42.565 | Initializing build environment. This may take up to a few minutes to complete
-- | --
20:47:47.700 | Success: Finished initializing build environment
20:47:47.700 | Cloning repository...
20:47:48.971 | Success: Finished cloning repository files
20:47:49.191 | Installing dependencies
20:47:49.193 | Python version set to 2.7
20:47:50.014 | Downloading and installing node v16.13.0...
20:47:50.133 | Downloading https://nodejs.org/dist/v16.13.0/node-v16.13.0-linux-x64.tar.xz...
20:47:50.536 | Computing checksum with sha256sum
20:47:50.673 | Checksums matched!
20:47:53.365 | Now using node v16.13.0 (npm v8.1.0)
20:47:53.420 | Started restoring cached build plugins
20:47:53.422 | Finished restoring cached build plugins
20:47:53.522 | Attempting ruby version 2.7.1, read from environment
20:47:54.360 | Using ruby version 2.7.1
20:47:54.598 | Using PHP version 5.6
20:47:54.624 | 5.2 is already installed.
20:47:54.629 | Using Swift version 5.2
20:47:54.629 | Started restoring cached node modules
20:47:54.632 | Finished restoring cached node modules
20:47:54.897 | Installing NPM modules using NPM version 8.1.0
20:48:01.287 |  
20:48:01.287 | added 231 packages, and audited 232 packages in 6s
20:48:01.287 |  
20:48:01.287 | 32 packages are looking for funding
20:48:01.287 | run `npm fund` for details
20:48:01.289 |  
20:48:01.289 | found 0 vulnerabilities
20:48:01.297 | NPM modules installed
20:48:01.587 | Installing Hugo 0.54.0
20:48:02.363 | Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
20:48:02.364 | Started restoring cached go cache
20:48:02.367 | Finished restoring cached go cache
20:48:02.387 | go version go1.14.4 linux/amd64
20:48:02.392 | go version go1.14.4 linux/amd64
20:48:02.393 | Installing missing commands
20:48:02.393 | Verify run directory
20:48:02.393 | Executing user command: npm run build
20:48:02.661 |  
20:48:02.661 | > svelte-etude@0.0.1 build
20:48:02.661 | > svelte-kit build
20:48:02.661 |  
20:48:02.970 | vite v2.6.14 building for production...
20:48:03.061 | transforming...
20:48:03.793 | ✓ 18 modules transformed.
20:48:03.856 | rendering chunks...
20:48:03.878 | .svelte-kit/output/client/_app/manifest.json                        2.00 KiB
20:48:03.880 | .svelte-kit/output/client/_app/start-68f2c803.js                    18.87 KiB / gzip: 6.91 KiB
20:48:03.880 | .svelte-kit/output/client/_app/layout.svelte-31c3b14a.js            0.53 KiB / gzip: 0.35 KiB
20:48:03.880 | .svelte-kit/output/client/_app/error.svelte-efc8e81b.js             1.56 KiB / gzip: 0.74 KiB
20:48:03.881 | .svelte-kit/output/client/_app/pages/index.svelte-1afec7d0.js       6.75 KiB / gzip: 2.38 KiB
20:48:03.881 | .svelte-kit/output/client/_app/pages/Kytaa.svelte-fdb2f783.js       0.62 KiB / gzip: 0.37 KiB
20:48:03.883 | .svelte-kit/output/client/_app/pages/script.svelte-a33ffe2c.js      0.26 KiB / gzip: 0.22 KiB
20:48:03.883 | .svelte-kit/output/client/_app/assets/start-61d1577b.css            0.16 KiB / gzip: 0.15 KiB
20:48:03.883 | .svelte-kit/output/client/_app/pages/eee/index.svelte-c4f02988.js   12.45 KiB / gzip: 0.34 KiB
20:48:03.883 | .svelte-kit/output/client/_app/chunks/vendor-a2b907d2.js            8.28 KiB / gzip: 3.32 KiB
20:48:03.888 | vite v2.6.14 building SSR bundle for production...
20:48:03.991 | transforming...
20:48:04.570 | ✓ 19 modules transformed.
20:48:04.603 | rendering chunks...
20:48:04.611 | .svelte-kit/output/server/app.js                      0.07 KiB
20:48:04.611 | .svelte-kit/output/server/chunks/app-fdc49c5a.js      49.79 KiB
20:48:04.611 | .svelte-kit/output/server/chunks/script-32c69c0b.js   0.10 KiB
20:48:04.612 | .svelte-kit/output/server/chunks/layout-d052fc8d.js   0.23 KiB
20:48:04.612 | .svelte-kit/output/server/chunks/error-c61b9601.js    0.71 KiB
20:48:04.612 | .svelte-kit/output/server/chunks/index-0976cc34.js    3.50 KiB
20:48:04.612 | .svelte-kit/output/server/chunks/Kytaa-f0606b4d.js    0.30 KiB
20:48:04.612 | .svelte-kit/output/server/chunks/script-fb72a225.js   0.27 KiB
20:48:04.612 | .svelte-kit/output/server/chunks/index-cc175cf9.js    6.26 KiB
20:48:04.614 |  
20:48:04.614 | Run npm run preview to preview your production build locally.
20:48:04.623 |  
20:48:04.623 | > Using @sveltejs/adapter-static
20:48:04.639 | > 404 /src/routes/style.scss (linked from /)
20:48:04.639 | Error: 404 /src/routes/style.scss (linked from /)
20:48:04.639 | at file:///opt/buildhome/repo/node_modules/@sveltejs/kit/dist/chunks/index4.js:86:11
20:48:04.639 | at visit (file:///opt/buildhome/repo/node_modules/@sveltejs/kit/dist/chunks/index4.js:217:5)
20:48:04.639 | at async visit (file:///opt/buildhome/repo/node_modules/@sveltejs/kit/dist/chunks/index4.js:288:6)
20:48:04.639 | at async prerender (file:///opt/buildhome/repo/node_modules/@sveltejs/kit/dist/chunks/index4.js:298:6)
20:48:04.639 | at async Object.prerender (file:///opt/buildhome/repo/node_modules/@sveltejs/kit/dist/chunks/index4.js:363:4)
20:48:04.639 | at async adapt (file:///opt/buildhome/repo/node_modules/@sveltejs/adapter-static/index.js:13:4)
20:48:04.640 | at async adapt (file:///opt/buildhome/repo/node_modules/@sveltejs/kit/dist/chunks/index4.js:388:2)
20:48:04.640 | at async file:///opt/buildhome/repo/node_modules/@sveltejs/kit/dist/cli.js:891:5
20:48:04.652 | Failed: build command exited with code: 1

</pre>
</body>
</html>
